FROM node:14-alpine

ENV APP_PATH /var/app
ENV REACT_PORT 3100

COPY ./docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

WORKDIR $APP_PATH

EXPOSE $REACT_PORT

CMD ["npm", "start"]